DELIMITER $$
CREATE PROCEDURE la_crime_report_P (WEEKNUM INT)
BEGIN
INSERT INTO la_crime_report_t (
    REPORT_NO,
    INCIDENT_TIME,
    COMPLAINT_TYPE,
    CCTV_FLAG,
    AREA_CODE,
    VICTIM_CODE,
    OFFICER_CODE,
    OFFENDER_CODE,
    OFFENDER_NAME,
    OFFENDER_AGE,
    OFFENDER_SEX,
    REPEATED_OFFENDER,
    NO_OF_OFFENCES,
    OFFENDER_RELATION,
    CRIME_CODE,
    CRIME_TYPE,
    WEAPON_CODE,
    WEAPON_DESC,
    CASE_STATUS_CODE,
    CASE_STATUS_DESC,
    WEEK_NUMBER
)
    SELECT DISTINCT
     REPORT_NO,
    INCIDENT_TIME,
    COMPLAINT_TYPE,
    CCTV_FLAG,
    AREA_CODE,
    VICTIM_CODE,
    OFFICER_CODE,
    OFFENDER_CODE,
    OFFENDER_NAME,
    OFFENDER_AGE,
    OFFENDER_SEX,
    REPEATED_OFFENDER,
    NO_OF_OFFENCES,
    OFFENDER_RELATION,
    CRIME_CODE,
    CRIME_TYPE,
    WEAPON_CODE,
    WEAPON_DESC,
    CASE_STATUS_CODE,
    CASE_STATUS_DESC,
    WEEK_NUMBER
FROM la_crime_t WHERE WEEK_NUMBER = WEEKNUM;

END$$

DELIMITER ;

