DELIMITER $$ 
CREATE PROCEDURE la_crime_location_p ()
BEGIN
INSERT INTO location_t (
	AREA_CODE,
	AREA_NAME,
	CCTV_COUNT,
	POPULATION_DENSITY,
	ROUNDS_PER_DAY 
)
SELECT DISTINCT
	AREA_CODE,
	AREA_NAME,
	CCTV_COUNT,
	POPULATION_DENSITY,
	ROUNDS_PER_DAY 
FROM la_crime_t WHERE AREA_CODE NOT IN ( SELECT DISTINCT AREA_CODE FROM la_crime_location_t);

END;